/** 16x16 desktop icons, drawn as ascii art in the default colors. */
import { HUES } from "./ui";

const KEY: Record<string, string> = {
  K: HUES.black, W: HUES.white, Y: HUES.yellow, O: HUES.orange, R: HUES.red, B: HUES.blue,
  S: "#c9c5d1", G: HUES.gray, E: HUES.green, T: HUES.teal, U: "#9fd0f0", P: HUES.purple,
};

function sprite(art: string) {
  const rows = art.trim().split(/\s+/);
  const w = 16, h = 16;
  const px = new Uint8ClampedArray(w * h * 4);
  rows.forEach((row, y) => {
    for (let x = 0; x < w; x++) {
      const hex = KEY[row[x] ?? "."];
      if (!hex) continue;
      const i = (y * w + x) * 4;
      px[i] = parseInt(hex.slice(1, 3), 16);
      px[i + 1] = parseInt(hex.slice(3, 5), 16);
      px[i + 2] = parseInt(hex.slice(5, 7), 16);
      px[i + 3] = 255;
    }
  });
  return px;
}

export const icons = {
  folder: sprite(`
    ................
    ................
    ..KKKKK.........
    .KOOOOOK........
    .KOOOOOOKKKKKKK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KYYYYYYYYYYYYK.
    .KKKKKKKKKKKKKK.
    ................
    ................`),
  file: sprite(`
    ...KKKKKKK......
    ...KWWWWWKK.....
    ...KWWWWWKWK....
    ...KWWWWWKKKK...
    ...KWWWWWWWWK...
    ...KWSSSSSWWK...
    ...KWWWWWWWWK...
    ...KWSSSSSSWK...
    ...KWWWWWWWWK...
    ...KWSSSSSSWK...
    ...KWWWWWWWWK...
    ...KWSSSSWWWK...
    ...KWWWWWWWWK...
    ...KKKKKKKKKK...
    ................
    ................`),
  program: sprite(`
    ................
    .KKKKKKKKKKKKKK.
    .KBBBBBBBBBBBBK.
    .KKKKKKKKKKKKKK.
    .KWWWWWWWWWWWWK.
    .KWWWWWRWWWWWWK.
    .KWWWWRRRWWWWWK.
    .KWWWRRRRRWWWWK.
    .KWWRRRRRRRWWWK.
    .KWWWRRRRRWWWWK.
    .KWWWWRRRWWWWWK.
    .KWWWWWRWWWWWWK.
    .KWWWWWWWWWWWWK.
    .KKKKKKKKKKKKKK.
    ................
    ................`),
  picture: sprite(`
    ................
    .KKKKKKKKKKKKKK.
    .KUUUUUUUUUUUUK.
    .KUUUUUUUUYYUUK.
    .KUUUUUUUUYYUUK.
    .KUUUUUUUUUUUUK.
    .KUUUUEUUUUUUUK.
    .KUUUEEEUUUUUUK.
    .KUUEEEEEUUEUUK.
    .KUEEEEEEEEEEUK.
    .KEEEEEEEEEEEEK.
    .KEEEEEEEEEEEEK.
    .KKKKKKKKKKKKKK.
    ................
    ................
    ................`),
  terminal: sprite(`
    ................
    .KKKKKKKKKKKKKK.
    .KSSSSSSSSSSSSK.
    .KKKKKKKKKKKKKK.
    .KKKKKKKKKKKKKK.
    .KKEKKKKKKKKKKK.
    .KKKEKKKKKKKKKK.
    .KKKKEKKKKKKKKK.
    .KKKEKKKKKKKKKK.
    .KKEKKEEEEKKKKK.
    .KKKKKKKKKKKKKK.
    .KKKKKKKKKKKKKK.
    .KKKKKKKKKKKKKK.
    ................
    ................
    ................`),
  /** Drawn over the bottom-left corner of linked things. */
  link: sprite(`
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    KKKKKKK.........
    KWWWWWK.........
    KWWKKKK.........
    KWWWKKK.........
    KWWKWKK.........
    KWKWWWK.........
    KKKKKKK.........
    ................`),
};
